### ISSUE TITLE
Interpolation on different size

### ISSUE THREAD

**Issue by sayannath** [sayannath/MobileViT-GSoC#3]
In the original paper implementation of MobileViT, this is [how](https://github.com/apple/ml-cvnets/blob/d38a116fe134a8cd5db18670764fdaafd39a5d4f/cvnets/modules/mobilevit_block.py#L127) the interpolation is taking place. 

The interpolation is taking place in the `feature_map` part. 

We need to build models based on the input size. 

CC: @sayakpaul @gustheman

**Comment by sayakpaul** [comment]
That is totally fine.

**Comment by sayannath** [comment]
Latest PR: https://github.com/sayannath/MobileViT-GSoC/pull/2
