### ISSUE TITLE
Check outputs of each layer in MobileViT

### ISSUE THREAD

**Issue by sayannath** [sayannath/MobileViT-GSoC#4]
How to check the output of every layer? Suppose my input to my model is this.

```python
image = tf.ones((256, 256, 3))
```
it is returning me an array of 1000 elements with different probabilities.

CC: @sayakpaul

**Comment by sayakpaul** [comment]
For TensorFlow models, you have the following options:

* Return a dictionary from the main model class where the keys would be the block / layers names and the values would be the outputs. This is only possible if your model is implemented subclassing from `tf.keras.Model`. 

* Take each layer and test them in isolation.

**Comment by sayannath** [comment]
As the layers are implemented using the Functional API, so we need to test each layer in isolation. For that, we just need to return the output of each layer right? And one more thing, is it okay to take an input tensor like this?

```python
image = tf.ones((256, 256, 3))
```

For Pytorch as well the process remains the same right?

**Comment by sayakpaul** [comment]
Yup. Same. Just ensure that both the models (your TF implementation and the original PT implementation) operate on the same inputs.
